"""G-11: turn the human queue into tickets and bring decisions back.

  python scripts/human_queue_issues.py --queue out/human_queue.json --repo owner/repo [--dry-run]
      one GitHub issue per queue item (label from --label, deduplicated by the item's stable key
      carried as an HTML marker in the body); existing open tickets are left alone.
  python scripts/human_queue_issues.py --repo owner/repo --sync-decisions [--dry-run]
      closed tickets carrying decision:true-positive or decision:false-positive become
      calib/decisions/<key>.json, and calib/decisions/backlog.json records the open count so the
      pipeline can tighten when the backlog is over the limit.

Uses the `gh` CLI (present on GitHub runners; needs GH_TOKEN with issues: write). Nothing here
ever approves a finding; humans decide on the ticket, the pipeline only reads the outcome.
"""

from __future__ import annotations

import argparse
import datetime as dt
import json
import re
import shutil
import subprocess
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
MARKER = "<!-- mara-hq:{key} -->"
MARKER_RE = re.compile(r"<!-- mara-hq:([0-9a-f]{12}) -->")
DECISION_LABELS = {"decision:true-positive": "true_positive", "decision:false-positive": "false_positive"}


class GhError(RuntimeError):
    pass


def gh(args: list[str], *, dry_run: bool = False, mutating: bool = False) -> str:
    exe = shutil.which("gh")
    if not exe:
        raise GhError("gh CLI not found on PATH")
    if dry_run and mutating:
        print("  [dry-run] gh " + " ".join(args))
        return ""
    cp = subprocess.run([exe, *args], capture_output=True, text=True, check=False)
    if cp.returncode != 0:
        raise GhError(f"gh {' '.join(args[:3])} failed: {cp.stderr.strip()[-500:]}")
    return cp.stdout


def ensure_labels(repo: str, label: str, dry_run: bool) -> None:
    for name, color, desc in ((label, "d93f0b", "MARA finding waiting for a human decision"),
                              ("decision:true-positive", "0e8a16", "Human decision: real vulnerability"),
                              ("decision:false-positive", "6a737d", "Human decision: not a vulnerability")):
        gh(["label", "create", name, "--force", "--color", color, "--description", desc, "--repo", repo], dry_run=dry_run, mutating=True)


def open_tickets(repo: str, label: str) -> dict[str, int]:
    out = gh(["issue", "list", "--repo", repo, "--label", label, "--state", "open", "--limit", "500", "--json", "number,body"])
    keys: dict[str, int] = {}
    for issue in json.loads(out or "[]"):
        m = MARKER_RE.search(issue.get("body") or "")
        if m:
            keys[m.group(1)] = issue["number"]
    return keys


def ticket_body(item: dict, target: str) -> str:
    L = [MARKER.format(key=item["key"]), f"**MARA human queue** · target `{target}` · finding {item['finding_id']} · key `{item['key']}`", "",
         f"- Why: {', '.join(item['reasons'])}",
         f"- {item['dimension']} · {item['cwe']} · `{item['file']}:{item['line']}` · tier {item['tier']} · CVSS {item['cvss4_score']} {item['cvss4_severity']} · SSVC {item['ssvc_decision']}",
         f"- Consensus {item['weighted_score']} (tp {item['votes_tp']} / fp {item['votes_fp']} / human {item['votes_human']}) · alpha {item['krippendorff_alpha']}",
         f"- Found by {', '.join(item['finder_families'])} · reachability {item['reachability']}: {item['reachability_argument']}",
         f"- Attacker path: {item['exploit_sketch']}", f"- Quote: `{item['quote']}`"]
    if item.get("skeptic"):
        s = item["skeptic"]
        L.append(f"- Skeptic ({s['family']}): **{s['verdict']}** — {s['reason']}" + (f" · control: {s['sanitizer_or_control']}" if s.get("sanitizer_or_control") else ""))
    if item.get("redteam"):
        r = item["redteam"]
        L.append(f"- Red team ({r['family']}): exploitable **{r['exploitable']}** — {r['preconditions']}")
    if item.get("judge_votes"):
        L += ["- Judges:"] + [f"  - {v['family']} [{v['pass']}]{' (self-family)' if v.get('self_family') else ''}: **{v['verdict']}** {v['severity_band']} — {v['reason']}"
                              for v in item["judge_votes"]]
    L += ["", "**Decide:** add label `decision:true-positive` or `decision:false-positive`, then close. "
          "The decision is written to `calib/decisions/` on the next sync and feeds calibration. Do not close without a decision label.",
          "", "---", "_Generated by [Claude Code](https://claude.ai/code)_"]
    return "\n".join(L)


def create_tickets(queue_path: Path, repo: str, label: str, dry_run: bool) -> tuple[int, int]:
    q = json.loads(queue_path.read_text(encoding="utf-8"))
    items, target = q.get("items", []), q.get("target", "")
    if not items:
        print("human queue is empty; nothing to file")
        return 0, 0
    ensure_labels(repo, label, dry_run)
    existing = {} if dry_run else open_tickets(repo, label)
    created = skipped = 0
    for it in items:
        if it["key"] in existing:
            print(f"  {it['finding_id']} key {it['key']}: open ticket #{existing[it['key']]} exists, skipping")
            skipped += 1
            continue
        body_file = Path(f".mara-hq-{it['key']}.md")
        body_file.write_text(ticket_body(it, target), encoding="utf-8")
        try:
            gh(["issue", "create", "--repo", repo, "--label", label, "--title", f"[MARA human queue] {it['finding_id']} · {it['title'][:80]}",
                "--body-file", str(body_file)], dry_run=dry_run, mutating=True)
        finally:
            body_file.unlink(missing_ok=True)
        created += 1
    return created, skipped


def sync_decisions(repo: str, label: str, decisions_dir: Path, backlog_file: Path, dry_run: bool) -> tuple[int, int]:
    closed = json.loads(gh(["issue", "list", "--repo", repo, "--label", label, "--state", "closed", "--limit", "500",
                            "--json", "number,body,labels,closedAt,url"]) or "[]")
    decisions_dir.mkdir(parents=True, exist_ok=True)
    written = 0
    for issue in closed:
        m = MARKER_RE.search(issue.get("body") or "")
        if not m:
            continue
        labels = {lab["name"] for lab in issue.get("labels", [])}
        decision = next((DECISION_LABELS[x] for x in labels if x in DECISION_LABELS), None)
        if decision is None:
            print(f"  issue #{issue['number']} closed without a decision label; ignored")
            continue
        key = m.group(1)
        meta = re.search(r"target `([^`]*)` · finding (F-\d+)", issue.get("body") or "")
        loc = re.search(r"· (CWE-\d+) · `([^`:]+):(\d+)`", issue.get("body") or "")
        record = {"key": key, "decision": decision, "issue": issue["number"], "url": issue.get("url"), "decided_at": issue.get("closedAt"),
                  "target": meta.group(1) if meta else "", "finding_id": meta.group(2) if meta else "",
                  "cwe": loc.group(1) if loc else "", "file": loc.group(2) if loc else "", "line": int(loc.group(3)) if loc else 0}
        path = decisions_dir / f"{key}.json"
        if dry_run:
            print(f"  [dry-run] would write {path}: {decision}")
        else:
            path.write_text(json.dumps(record, ensure_ascii=False, indent=2) + "\n", encoding="utf-8")
        written += 1
    open_count = len(open_tickets(repo, label))
    backlog = {"open": open_count, "updated_at": dt.datetime.now(dt.UTC).isoformat(timespec="seconds"), "label": label, "repo": repo}
    if dry_run:
        print(f"  [dry-run] backlog: {backlog}")
    else:
        backlog_file.parent.mkdir(parents=True, exist_ok=True)
        backlog_file.write_text(json.dumps(backlog, indent=2) + "\n", encoding="utf-8")
    return written, open_count


def main() -> int:
    ap = argparse.ArgumentParser(description=__doc__.splitlines()[0])
    ap.add_argument("--queue", type=Path, help="out/human_queue.json from a review; omit with --sync-decisions only")
    ap.add_argument("--repo", required=True, help="owner/repo")
    ap.add_argument("--label", default="mara-human-queue")
    ap.add_argument("--decisions-dir", type=Path, default=ROOT / "calib" / "decisions")
    ap.add_argument("--backlog-file", type=Path, default=ROOT / "calib" / "decisions" / "backlog.json")
    ap.add_argument("--sync-decisions", action="store_true")
    ap.add_argument("--dry-run", action="store_true", help="print the gh commands instead of running the mutating ones")
    args = ap.parse_args()
    try:
        if args.queue:
            created, skipped = create_tickets(args.queue, args.repo, args.label, args.dry_run)
            print(f"tickets: {created} created, {skipped} already open")
        if args.sync_decisions:
            written, open_count = sync_decisions(args.repo, args.label, args.decisions_dir, args.backlog_file, args.dry_run)
            print(f"decisions: {written} written to {args.decisions_dir}; open backlog {open_count}")
        if not args.queue and not args.sync_decisions:
            ap.error("give --queue and/or --sync-decisions")
    except GhError as e:
        print(f"ERROR: {e}", file=sys.stderr)
        return 1
    return 0


if __name__ == "__main__":
    sys.exit(main())
